[package]
name = "mask"
version = "0.9.0"
description = "A CLI task runner defined by a simple markdown file"
authors = ["Jake Deichert <git@jakedeichert.com>"]
repository = "https://github.com/jakedeichert/mask"
readme = "README.md"
keywords = ["cli", "task", "command", "make", "markdown"]
categories = ["command-line-interface", "command-line-utilities", "development-tools::build-utils", "parser-implementations"]
edition = "2018"
exclude = ["maskfile.md", ".gitignore", "CHANGELOG.md", "test/**", ".circleci/**"]
license = "MIT"

[lib]
name = "mask"
path = "src/lib.rs"

[dependencies]
colored = "1.8.0"                                                       # https://github.com/mackwic/colored
pulldown-cmark = { version = "0.5", default-features = false }          # https://github.com/raphlinus/pulldown-cmark

[dependencies.clap]																# https://github.com/clap-rs/clap
version = "2.33.0"
features = ["wrap_help"]

[dev-dependencies]
assert_cmd = "0.11.1"                                                   # https://github.com/assert-rs/assert_cmd
assert_fs = "0.11.3"                                                    # https://github.com/assert-rs/assert_fs
predicates = "1.0.1"                                                    # https://github.com/assert-rs/predicates-rs
